#!/usr/bin/env python3
"""Builds css/spin-hud.css from tools/spin-hud.src.css.

The Spin HUD is laid out on the reference video's canvas (1906x998). Every length in the
source is written in reference pixels with a `u` suffix (e.g. `344u`); this script turns
them into calc(var(--u)*344), where --u (px per reference px) is set from JS on resize.
"""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "tools/spin-hud.src.css").read_text()
out = re.sub(r"(?<![\w#])(-?(?:\d+(?:\.\d+)?|\.\d+))u\b", lambda m: f"calc(var(--u)*{m.group(1)})", src)
(root / "android/app/src/main/assets/css/spin-hud.css").write_text("/* Generated by tools/build-spin-hud.py — edit tools/spin-hud.src.css */\n" + out)
print("ok", len(out))
