# Packs the Blender-exported weapon GLBs into js/data/WeaponModels.js (base64, keyed by weapon name).
import base64, json, os, sys
SRC = sys.argv[1]
OUT = "android/app/src/main/assets/js/data/WeaponModels.js"
NAMES = {"machete": "Machete", "mp5": "MP5", "bow": "Bow", "riot_breaker": "Riot Breaker", "crimson_ak": "Crimson AK",
         "firestarter": "Hellfire", "wraith_m4a1": "Wraith M4A1", "bloodfang": "Bloodfang", "titanbreaker": "Titanbreaker",
         "cerberus_laser": "Cerberus Laser", "frostbite": "Frostbite", "stormpiercer": "Stormpiercer", "thundergrave": "Thundergrave",
         "doomsday_launcher": "Doomsday Launcher", "widowmaker": "Widowmaker", "quantum_annihilator": "Quantum Annihilator",
         "hellfire_incarnate": "Fire Incarnation", "wraithpiercer": "Wraithpiercer", "dawn_spear": "Dawn Spear",
         "heavenfall_bazooka": "Heavenfall Bazooka", "absolute_zero": "Absolute Zero", "grenade": "Grenade",
         "demonic_fury": "Demonic Fury", "angelic_specter": "Angelic Specter",
         "proj_bow": "Proj Bow", "proj_stormpiercer": "Proj Stormpiercer", "proj_wraithpiercer": "Proj Wraithpiercer",
         "proj_doomsday": "Proj Doomsday Launcher", "proj_heavenfall": "Proj Heavenfall Bazooka",
         "shell_9mm": "Shell 9mm", "shell_762": "Shell 7.62", "shell_556": "Shell 5.56", "shell_50": "Shell .50", "shell_12g": "Shell 12g"}
data = {}
for slug, name in NAMES.items():
    p = os.path.join(SRC, slug + ".glb")
    if os.path.exists(p):
        data[name] = base64.b64encode(open(p, "rb").read()).decode()
with open(OUT, "w") as f:
    f.write("// Voxel weapon models built in Blender (tools/blender/weapons_build.py) from the WEAPON UV TEMPLATES.\n")
    f.write("// GLB files as base64 so they load on file:// (Android WebView, Electron). Generated by tools/pack_weapons.py.\n")
    f.write("window.DR_WEAPON_GLB = " + json.dumps(data, indent=0) + ";\n")
print(len(data), os.path.getsize(OUT))
