# Packs the Blender-exported prop GLBs (tools/blender/props_build.py) into js/data/PropModels.js.
import base64, json, os, sys
SRC = sys.argv[1]
OUT = "android/app/src/main/assets/js/data/PropModels.js"
data = {}
for f in sorted(os.listdir(SRC)):
    if f.endswith(".glb"):
        data[f[:-4]] = base64.b64encode(open(os.path.join(SRC, f), "rb").read()).decode()
with open(OUT, "w") as fh:
    fh.write("// Environment props built in Blender (tools/blender/props_build.py): trees, cars, igloo, rocket.\n")
    fh.write("// GLB as base64 so they load on file:// (Android WebView, Electron). Generated by tools/pack_props.py.\n")
    fh.write("window.DR_PROP_GLB = " + json.dumps(data, indent=0) + ";\n")
print(len(data), os.path.getsize(OUT))
